### ISSUE TITLE
Handle readme title

### ISSUE THREAD

**Issue by yozhgoor** [orium/cargo-rdme#38]
It would be great the handle the title of the readme.
`cargo-readme` automatically add the crate name as the title of the readme like this:

```rust
//! Description of my crate
//! 
//! Examples
//!
//! This is an example
```

will output:

```markdown
# crate name

Description of my crate

## Examples

This is an example
```

**Comment by orium** [comment]
I can imagine people wanting other title that is not the crate name.  For instance for my crate [rpds](https://raw.githubusercontent.com/orium/rpds/master/README.md) I use `Rust Persistent Data Structures` as the title.

One way to support this is by configuration.  Another, which I'm inclined to, because it is more general, is simply have the title in the `README.md`, like this:

```markdown
# Whatever title I want

<!-- cargo-rdme -->
```

In which case I need to bump the "section-level" of the markdown inserted in the README.  For instance, if the rustdoc is 

```markdown
Brief description

# Another section 
```

the resulting `README.md` should be 

```markdown
# Whatever title I want

<!-- cargo-rdme start -->

Brief description

## Another section 

<!-- cargo-rdme end -->
```

**Comment by yozhgoor** [comment]
> I can imagine people wanting other title that is not the crate name. For instance for my crate [rpds](https://raw.githubusercontent.com/orium/rpds/master/README.md) I use `Rust Persistent Data Structures` as the title.
> 
> One way to support this is by configuration. Another, which I'm inclined to, because it is more general, is simply have the title in the `README.md`, like this:
> 
> ```gfm
> # Whatever title I want
> 
> 
> ```
> 
> In which case I need to bump the "section-level" of the markdown inserted in the README. For instance, if the rustdoc is
> 
> ```rust
> //! Brief description
> //!
> //! # Another section
> ```

This is the solution I currently use but i bump manually. Maybe a `readme-title` value in the config file so we can handle the three cases:

* I don't want any title
* I take the default title (the crate name)
* I want a custom title

So the bump can be handle easily

**Comment by yozhgoor** [comment]
Nice idea! If i can free some time for this next weeks i would look further at the code and open a PR i you don't mind.

**Comment by orium** [comment]
Sure.  Take a look at `cargo_rdme_line_iterator()`.  It returns information about the README.  It can be generalized.  Currently it returns this  enum

```rust
enum CargoRdmeLine<'a> {
    Line(&'a str),
    MarkerCargoRdme,
    MarkerCargoRdmeStart,
    MarkerCargoRdmeEnd,
}
```

It can be extended to to have a variant like `Section { level: u8 }` or something like that.  Then function that calls it (`inject_doc_in_readme`) can use that to know which level it is on.

The function `inject_doc_in_readme()`, can then do something like:

```rust
inject(&mut new_readme, increase_section_level(doc, base_level));
```

where `increase_section_level` is something like `fn increase_section_level(doc: &Doc, u8: section_level) -> Doc`.  Try to implement the `increase_section_level` using `pulldown-cmark` for parsing.  I'm trying to avoid doing my own parsing as much as possible, since markdown looks very simple but has tricky edge cases.

Make sure to add a "system test" in the `tests` directory in the root of the project.

Ping me if you need any help.

**Comment by orium** [comment]
Let me know if you are still interested in implementing this, otherwise I can give it a go myself.

**Comment by yozhgoor** [comment]
I'm sorry, didn't have much time for this lately. 
I did fork the project but didn't go through the code already.
